name: Selcuk Spor Güncelleyici

on:
  schedule:
    - cron: '0 */3 * * *' # Her 3 saatte bir çalışır
  workflow_dispatch: # Manuel tetikleme butonu ekler

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu Çek (Checkout)
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install requests urllib3

      - name: Scripti Çalıştır
        # Buradaki dosya ismi, 2. adımda oluşturduğunla AYNI olmalı
        run: python deathless-selcuk.py

      - name: Dosyayı Kaydet (Commit & Push)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add deathless-selcuk.m3u
          git commit -m "Liste Güncellendi" || exit 0
          git push
